Step 4: Refactor ingredient construction
juiceinc/recipe pull request #198
Opened 2023-03-09 13:55 UTC by chrisgemignani

This PR refactors how we create ingredients from config. 

Dimensions and Metrics now support a filter property which can be used to generate `Ingredient.filters` that will be applied when this ingredient is used. While this can be confusing it's also very powerful and has been specifically requested by users of the library.

We will use this filter property to to join multiple tables. 

### Other changes

A remnant of ingredient config version 1 was removed. Ingredients no longer require a `_version` property.

2023-03-10 21:49 UTC, radix commented
@chrisgemignani Because you used a squash-merge on the previous PR, this PR is now based on the wrong commits and has too much stuff in it. This branch needs to be rebased (should be an easy `git rebase -i` where you just delete all the commits that came from the previous branches).

2023-03-13 13:04 UTC, chrisgemignani commented
@radix I fixed this and the following PR.

2023-03-13 14:46 UTC, chrisgemignani commented on recipe/schemas/parsed_constructors.py
> +        return "dt_day_conv"
This is a change; it's a slight improvement on how this worked before but hardcoding these formats is still yuck.

2023-03-13 14:47 UTC, chrisgemignani commented on recipe/schemas/parsed_constructors.py
> +            ingr_dict["filters"] = [expr]
This is new behavior that ingredient conversion did not do before this PR.

2023-03-13 20:20 UTC, radix requested changes
just one simple request

2023-03-16 19:53 UTC, radix approved these changes
oo, I like the new date_aggregation. good incremental step. :+1:

2023-03-17 08:29 UTC, merged